"""migrate to platform_role

Revision ID: 311f07a59e20
Revises: c67f11430cc8
Create Date: 2026-10-07 04:14:18.697688

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '311f07a59e20'
down_revision: Union[str, None] = 'c67f11430cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('platform_role', sa.String(length=50), server_default='normal_user', nullable=True))
    op.execute("UPDATE users SET platform_role = 'super_user' WHERE is_superuser = true")
    op.execute("UPDATE users SET platform_role = 'normal_user' WHERE is_superuser = false")
    op.alter_column('users', 'platform_role', nullable=False)
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.execute("UPDATE users SET is_superuser = true WHERE platform_role = 'super_user'")
    op.execute("UPDATE users SET is_superuser = false WHERE platform_role != 'super_user'")
    op.alter_column('users', 'is_superuser', nullable=False)
    op.drop_column('users', 'platform_role')
    # ### end Alembic commands ###
