"""add_platform_settings_and_integrations

Revision ID: 45ce9644c4e8
Revises: 2c03f339e0b5
Create Date: 2026-09-21 18:53:07.522817

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '45ce9644c4e8'
down_revision: Union[str, None] = '2c03f339e0b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('encrypted_credentials', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_integrations_name'), 'platform_integrations', ['name'], unique=True)
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allow_signups', sa.Boolean(), nullable=False),
    sa.Column('max_tenants_allowed', sa.Integer(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('maintenance_message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='platform_settings_id_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_ai_usage_records_created_at'), table_name='ai_usage_records')
    op.create_index(op.f('ix_ai_usage_records_id'), 'ai_usage_records', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.drop_index(op.f('ix_beta_deployments_industry'), table_name='beta_deployments')
    op.drop_index(op.f('ix_beta_deployments_is_deployed'), table_name='beta_deployments')
    op.create_index(op.f('ix_beta_deployments_id'), 'beta_deployments', ['id'], unique=False)
    op.create_index(op.f('ix_beta_feedback_id'), 'beta_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_business_info_id'), 'business_info', ['id'], unique=False)
    op.create_index(op.f('ix_chatbots_id'), 'chatbots', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.alter_column('invitations', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='memberrole', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'::character varying"))
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_id'), 'knowledge_sources', ['id'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.drop_index(op.f('ix_onboarding_checklists_organization_id'), table_name='onboarding_checklists')
    op.create_index(op.f('ix_onboarding_checklists_organization_id'), 'onboarding_checklists', ['organization_id'], unique=False)
    op.create_index(op.f('ix_onboarding_checklists_id'), 'onboarding_checklists', ['id'], unique=False)
    op.alter_column('organization_members', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='memberrole', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'::character varying"))
    op.create_index(op.f('ix_organization_members_id'), 'organization_members', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_integrations_id'), 'tenant_integrations', ['id'], unique=False)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_id'), 'webhook_endpoints', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_endpoints_id'), table_name='webhook_endpoints')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'avatar_url',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.drop_index(op.f('ix_tenant_integrations_id'), table_name='tenant_integrations')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organization_members_id'), table_name='organization_members')
    op.alter_column('organization_members', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='memberrole', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'::character varying"))
    op.drop_index(op.f('ix_onboarding_checklists_id'), table_name='onboarding_checklists')
    op.drop_index(op.f('ix_onboarding_checklists_organization_id'), table_name='onboarding_checklists')
    op.create_index(op.f('ix_onboarding_checklists_organization_id'), 'onboarding_checklists', ['organization_id'], unique=True)
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_knowledge_sources_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.alter_column('invitations', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='memberrole', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'::character varying"))
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_chatbots_id'), table_name='chatbots')
    op.drop_index(op.f('ix_business_info_id'), table_name='business_info')
    op.drop_index(op.f('ix_beta_feedback_id'), table_name='beta_feedback')
    op.drop_index(op.f('ix_beta_deployments_id'), table_name='beta_deployments')
    op.create_index(op.f('ix_beta_deployments_is_deployed'), 'beta_deployments', ['is_deployed'], unique=False)
    op.create_index(op.f('ix_beta_deployments_industry'), 'beta_deployments', ['industry'], unique=False)
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_ai_usage_records_id'), table_name='ai_usage_records')
    op.create_index(op.f('ix_ai_usage_records_created_at'), 'ai_usage_records', ['created_at'], unique=False)
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_platform_integrations_name'), table_name='platform_integrations')
    op.drop_table('platform_integrations')
    # ### end Alembic commands ###
