"""Add onboarding_completed to Organization

Revision ID: 84051b35a3a1
Revises: bf80b9f0a9d9
Create Date: 2026-10-06 19:28:07.533062

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '84051b35a3a1'
down_revision: Union[str, None] = 'bf80b9f0a9d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'onboarding_completed')
    # ### end Alembic commands ###
