"""add config_json to chatbots

Revision ID: bf80b9f0a9d9
Revises: 45ce9644c4e8
Create Date: 2026-09-23 20:34:35.371866

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf80b9f0a9d9'
down_revision: Union[str, None] = '45ce9644c4e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.alter_column('platform_integrations', 'provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('openrouter', 'openai', 'stripe', name='providerenum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('platform_integrations', 'provider',
               existing_type=sa.Enum('openrouter', 'openai', 'stripe', name='providerenum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('chatbots', 'config_json')
    # ### end Alembic commands ###
