"""Add chatbot template and knowledge association

Revision ID: c67f11430cc8
Revises: 84051b35a3a1
Create Date: 2026-10-07 03:40:40.654970

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'c67f11430cc8'
down_revision: Union[str, None] = '84051b35a3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('template_type', sa.String(length=50), nullable=True))
    op.add_column('knowledge_sources', sa.Column('chatbot_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_knowledge_sources_chatbot_id'), 'knowledge_sources', ['chatbot_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_sources', 'chatbots', ['chatbot_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_sources', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_sources_chatbot_id'), table_name='knowledge_sources')
    op.drop_column('knowledge_sources', 'chatbot_id')
    op.drop_column('chatbots', 'template_type')
    # ### end Alembic commands ###
