import React from 'react';
import Link from 'next/link';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white">
      {/* Simple Header */}
      <header className="border-b border-slate-200 py-4 px-6 md:px-12 flex items-center justify-between">
        <Link href="/" className="text-xl font-bold tracking-tight text-slate-900">
          Helio
        </Link>
        <nav className="space-x-4">
          <Link href="/privacy" className="text-sm font-medium text-slate-600 hover:text-slate-900 transition-colors">
            Privacy Policy
          </Link>
        </nav>
      </header>

      <main className="max-w-4xl mx-auto py-12 px-6 sm:py-20 lg:px-8">
        <h1 className="text-3xl md:text-5xl font-extrabold tracking-tight text-slate-900 mb-8">
          Terms of Service
        </h1>
        <div className="prose prose-slate prose-lg max-w-none text-slate-700 space-y-6">
          <p className="font-medium text-slate-900">Last Updated: {new Date().toLocaleDateString()}</p>
          
          <p>
            Welcome to Helio! These Terms of Service ("Terms") govern your use of the Helio website, products, and services (collectively, the "Services"). By accessing or using our Services, you agree to be bound by these Terms.
          </p>

          <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">1. Acceptance of Terms</h2>
          <p>
            By creating an account or otherwise accessing the Services, you accept these Terms and our Privacy Policy. If you are using the Services on behalf of an organization, you represent that you have the authority to bind that organization to these Terms.
          </p>

          <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">2. Description of Service</h2>
          <p>
            Helio provides an AI-powered chatbot platform that allows businesses to automate customer support, capture leads, schedule appointments via Google Calendar, and analyze conversation data. The Services include the dashboard, widget, API, and underlying AI routing technology.
          </p>

          <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">3. User Accounts</h2>
          <p>
            You must provide accurate information when registering for an account. You are responsible for safeguarding your account credentials. You agree to notify us immediately of any unauthorized use of your account.
          </p>

          <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">4. Acceptable Use</h2>
          <p>You agree not to use the Services to:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Violate any applicable laws, regulations, or third-party rights.</li>
            <li>Distribute spam, malware, or engage in phishing activities.</li>
            <li>Train other artificial intelligence models using data generated by Helio without explicit permission.</li>
            <li>Attempt to reverse-engineer, decompile, or bypass the security of the Services.</li>
          </ul>

          <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">5. Third-Party Integrations</h2>
          <p>
            Our Services interact with third-party platforms such as Google Calendar, OpenAI, and Anthropic. Your use of these integrations is governed by the respective terms of service and privacy policies of those third parties. We are not responsible for the availability or performance of these external services.
          </p>

          <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">6. Intellectual Property</h2>
          <p>
            Helio retains all rights, title, and interest in and to the Services, including all related intellectual property. You retain ownership of the data, documents, and content you upload to the Services (your "Knowledge Base"), but you grant Helio a license to use this data solely for the purpose of operating and improving the Services for you.
          </p>

          <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">7. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your access to the Services at any time, with or without notice, if we determine that you have violated these Terms.
          </p>

          <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">8. Disclaimer of Warranties & Limitation of Liability</h2>
          <p>
            The Services are provided "AS IS" without warranties of any kind. To the maximum extent permitted by law, Helio shall not be liable for any indirect, incidental, special, or consequential damages arising out of your use of the Services, including but not limited to loss of data, revenue, or business opportunities.
          </p>

          <h2 className="text-2xl font-bold text-slate-900 mt-10 mb-4">9. Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us at support@helio.chat.
          </p>
        </div>
      </main>
      
      <footer className="bg-slate-50 border-t border-slate-200 py-12 mt-12">
        <div className="max-w-4xl mx-auto px-6 text-center text-slate-500 text-sm">
          &copy; {new Date().getFullYear()} Helio Inc. All rights reserved.
        </div>
      </footer>
    </div>
  );
}
